### ISSUE TITLE
Adding map from gallery does not work, generates "No persistable permission grants found" security exception (on Android 10 phone)

### ISSUE THREAD

**Issue by jnareb** [WojciechKuz/Mappic#3]
When trying to add a new map from the _"Map list"_ activity with the "+" Floating Action Button, then selecting _"Choose from gallery"_, and selecting an image, the application does not go to the next step of adding points to use for orienting the map, but goes back to the original _"Map list"_ view without adding a new page. Sometimes the app crashes instead.

Adding map by taking the photo (_"New photo"_) works.

The problem happens on my Nokia 6.1 phone with Android 10 (API Level 29).

Examining logcat it at beginning everything looks all right:
```
>>> Opening AddMapActivity.
>>> open photo from gallery button clicked
>>> Selected URI: content://media/external/file/33616.
```

But then the process throws an exception:
```
FATAL EXCEPTION: main
    Process: pl.umk.mat.mappic, PID: 2316
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=523757530, result=-1, data=Intent { flg=0x1 clip={image/* video/* U:content://media/external/file/33616} }}
    to activity {pl.umk.mat.mappic/pl.umk.mat.mappic.addmap.AddMapActivity}: java.lang.SecurityException:
    No persistable permission grants found for UID 10500 and Uri content://media/external/file/33616 [user 0]
```
<details>

<summary>Detailed stack trace:</summary>

```
FATAL EXCEPTION: main
                                                                                                    Process: pl.umk.mat.mappic, PID: 2316
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=523757530, result=-1, data=Intent { flg=0x1 clip={image/* video/* U:content://media/external/file/33616} }} to activity {pl.umk.mat.mappic/pl.umk.mat.mappic.addmap.AddMapActivity}: java.lang.SecurityException: No persistable permission grants found for UID 10500 and Uri content://media/external/file/33616 [user 0]
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4846)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
                                                                                                    Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10500 and Uri content://media/external/file/33616 [user 0]
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2071)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2039)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1987)
                                                                                                    	at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
                                                                                                    	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2431)
                                                                                                    	at pl.umk.mat.mappic.addmap.features.images.PickPhoto.photoPicked(PickPhoto.kt:46)
                                                                                                    	at pl.umk.mat.mappic.addmap.features.images.PickPhoto.pickMedia$lambda$0(PickPhoto.kt:22)
                                                                                                    	at pl.umk.mat.mappic.addmap.features.images.PickPhoto.$r8$lambda$Uol0D8P_IWvxjM1xHcmqOtCBkbQ(Unknown Source:0)
                                                                                                    	at pl.umk.mat.mappic.addmap.features.images.PickPhoto$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887) 
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7397) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.uri.UriGrantsManagerService.takePersistableUriPermission(UriGrantsManagerService.java:328)
                                                                                                    	at android.app.IUriGrantsManager$Stub.onTransact(IUriGrantsManager.java:139)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1021)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:994)
```
</details>

Which then causes few further problems:
```
channel '6f7b8bb pl.umk.mat.mappic/pl.umk.mat.mappic.addmap.AddMapActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
channel '439a796 pl.umk.mat.mappic/pl.umk.mat.mappic.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
and
```
Fail to get file list pl.umk.mat.mappic
getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
```

It looks like the problem might be solved by the proposal in https://stackoverflow.com/a/49508047/46058 answer to the [java.lang.SecurityException on takePersistableUriPermission() (SAF)](https://stackoverflow.com/questions/37993762/java-lang-securityexception-on-takepersistableuripermission-saf) question on StackOverflow.

**Comment by WojciechKuz** [comment]
I implemented proposed solution and when testing I see no issues. If problem still exists, it will be reopened.
