### ISSUE TITLE
Step 2 (adding 1st point) in landscape mode does not show the map photo, ImageView is empty (NullPointerException)

### ISSUE THREAD

**Issue by jnareb** [WojciechKuz/Mappic#4]
When adding new map in the landscape (horizontal) mode, the step of adding the 1st point (for finding map scale, orientation, and position) shows empty space instead of the photo:

![Screenshot_20240207-142743](https://github.com/WojciechKuz/Mappic/assets/2706/c2d6e039-e093-4d0f-9e0d-53e0a7327da0)

Note: screenshot taken of with Polish locale.

When examining what happen with logcat, there is the following issue:

```
Exception dispatching input event.
Exception in MessageQueue callback: handleReceiveCallback
java.lang.NullPointerException: findViewById(...) must not be null
	at pl.umk.mat.mappic.addmap.shared_step2and3.Step2and3.getImageView(Step2and3.kt:89)
	at pl.umk.mat.mappic.addmap.shared_step2and3.Step2and3.viewSizeGet(Step2and3.kt:114)
	at pl.umk.mat.mappic.addmap.shared_step2and3.AddmapSteps2and3Utility.myViewClicked(AddmapSteps2and3Utility.kt:59)
	at pl.umk.mat.mappic.addmap.Step2Fragment.onViewCreated$lambda$2(Step2Fragment.kt:64)
	at pl.umk.mat.mappic.addmap.Step2Fragment.$r8$lambda$cjJXJmeTaRRyzYv8OoHUBBE8uHw(Unknown Source:0)
	at pl.umk.mat.mappic.addmap.Step2Fragment$$ExternalSyntheticLambda2.receiveMotionEvent(Unknown Source:2)
	at pl.umk.mat.mappic.common.myview.MyView.passMotionEvent(MyView.kt:58)
	at pl.umk.mat.mappic.common.myview.MyView.onTouchEvent(MyView.kt:51)
[...]
```

Also, there is an error earlier, but this one happens also in portrait mode where everything works:
```
>>> Rotation tag in image exif data not found. cannot display it correctly.
```

This is probably caused by the fact that the `ImageView` element in the portrait mode uses
```xml
android:id="@+id/imgMapView"
```
while the same element in the landscape mode layout uses
```xml
android:id="@+id/imgView"
```

The code assumes that the earlier id is correct:
```kotlin
    fun getImageView(): ImageView {
        return addMap.findViewById<ImageView>(R.id.imgMapView)
    }
```

**Note:** My smartphone is Nokia 6.1, with Android 10

**Comment by WojciechKuz** [comment]
Fixed on  `master` branch. Please wait for other issues to be resolved.
